backend:
  name: git-gateway
  branch: main

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "people"
    label: "People"
    folder: "content/authors"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }

  - name: "posts"
    label: "News"
    folder: "content/post"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/event"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }